// Code generated by MockGen. DO NOT EDIT.
// Source: kafka.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	message "github.com/ThreeDotsLabs/watermill/message"
	gomock "github.com/golang/mock/gomock"
)

// MockBrokerComponent is a mock of BrokerComponent interface.
type MockBrokerComponent struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerComponentMockRecorder
}

// MockBrokerComponentMockRecorder is the mock recorder for MockBrokerComponent.
type MockBrokerComponentMockRecorder struct {
	mock *MockBrokerComponent
}

// NewMockBrokerComponent creates a new mock instance.
func NewMockBrokerComponent(ctrl *gomock.Controller) *MockBrokerComponent {
	mock := &MockBrokerComponent{ctrl: ctrl}
	mock.recorder = &MockBrokerComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerComponent) EXPECT() *MockBrokerComponentMockRecorder {
	return m.recorder
}

// NewPublisher mocks base method.
func (m *MockBrokerComponent) NewPublisher() (message.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPublisher")
	ret0, _ := ret[0].(message.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewPublisher indicates an expected call of NewPublisher.
func (mr *MockBrokerComponentMockRecorder) NewPublisher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPublisher", reflect.TypeOf((*MockBrokerComponent)(nil).NewPublisher))
}

// NewSubscriber mocks base method.
func (m *MockBrokerComponent) NewSubscriber() (message.Subscriber, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewSubscriber")
	ret0, _ := ret[0].(message.Subscriber)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewSubscriber indicates an expected call of NewSubscriber.
func (mr *MockBrokerComponentMockRecorder) NewSubscriber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSubscriber", reflect.TypeOf((*MockBrokerComponent)(nil).NewSubscriber))
}
