#!/bin/bash
source "$(dirname "$0")/common.sh"

echo "==========================================="
echo "Watermill Tutorial - Docker Management"
echo "==========================================="
echo ""
print_header "Usage:"
echo "  make [target]"
echo ""
print_header "Main Targets:"
echo -e "  ${YELLOW}build${NC}            - Build Docker images"
echo -e "  ${YELLOW}start${NC}            - Start all services"
echo -e "  ${YELLOW}stop${NC}             - Stop all services"
echo -e "  ${YELLOW}restart${NC}          - Restart all services"
echo -e "  ${YELLOW}status${NC}           - Show service status"
echo -e "  ${YELLOW}clean${NC}            - Remove all containers and volumes"
echo ""
print_header "Logs:"
echo -e "  ${YELLOW}logs${NC}             - Show all logs (follow mode)"
echo -e "  ${YELLOW}logs-app${NC}         - Show app logs only"
echo -e "  ${YELLOW}logs-kafka${NC}       - Show Kafka logs only"
echo ""
print_header "Testing:"
echo -e "  ${YELLOW}test-producer${NC}    - Run Kafka producer (send messages)"
echo -e "  ${YELLOW}test-consumer${NC}    - Run Kafka consumer (receive messages)"
echo -e "  ${YELLOW}integration-test${NC} - Run full integration test suite"
echo ""
print_header "Aliases:"
echo -e "  ${YELLOW}up${NC}               - Same as 'start'"
echo -e "  ${YELLOW}down${NC}             - Same as 'stop'"
echo -e "  ${YELLOW}ps${NC}               - Same as 'status'"
echo -e "  ${YELLOW}rebuild${NC}          - Build and start"
echo -e "  ${YELLOW}reset${NC}            - Clean, build, and start"
echo ""
print_header "Examples:"
echo "  make build               # Build Docker images"
echo "  make start               # Start all services"
echo "  make integration-test    # Run full test suite"
echo "  make test-producer       # Send test messages to Kafka"
echo ""
